name: Auto Stock Filter

on:
  push:
  branches:
    -main
  schedule:
    # UTC07:30執行 (15:30的意思)
    - cron: '30 7 * * 1-5'
  workflow_dispatch: #手動檔不怕被系統ban

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 複製專案程式碼
      uses: actions/checkout@v3

    - name: 設定 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安裝所需套件
      run: |
        pip install yfinance pandas

    - name: 執行選股並產生網頁
      run: python filter.py

    - name: 將產生的網頁推送到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true